### ISSUE TITLE
boiled soy milk

### ISSUE THREAD

**Issue by cyraxan** [l33tmaan/vs-expandedfoods#10]
client crash and can't load after boiling soy milk  in Saucepan

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.4 (Stable)
Loaded Mods: advancedsmithing@1.2.0, weaponpackapatch@2.0.0, ancienttools@1.4.0, animalcages@2.0.6, armorrepair@1.0.3, Autorotor@1.1.2, axleinblocks@1.0.12, betterdrifters@2.1.3, buildingplus@1.1.2, chiseltools@1.3.1, cottagewindows@1.0.2, dragonflies@1.2.0, expandedfoods@1.5.3-pre.4, glassmaking@1.2.0, potatoes@1.0.8, leadroof@1.1.1, necessaries@1.1.1, neededthings@1.0.0, nightwatcher@1.2.0, oxygennotincluded@0.2.4, primitivesurvival@2.8.0, qptech@1.7.6, superfuel@2.0.7, locustmod@2.3.5, thecritterpack@0.7.6, tradeomat@1.6.0, viesblocks@2.0.2, viescraftmachines@1.17.0, game@1.16.4, alchemy@1.6.3, captureanimals@2.1.1, carrycapacity@0.6.5, drifteroverhaul@1.0.0, fromgoldencombs@1.3.8, helvehammerext@1.2.0, hudclock@2.7.0, lichen@1.6.0, medievalexpansion@3.7.1, moreanimals@1.2.2, morebags@1.0.0, outlawmod@1.1.0, petai@1.3.7, playercorpse@1.3.1, stonequarry@1.6.5, tpnet@1.5.1, translocatorlocator@1.0.2, usefulstuff@2.3.2, creative@1.16.4, survival@1.16.4, vsvillage@0.0.3, wildfarming@1.2.7, workbenchexpansion@1.4.1, xlib@0.6.8, xmelee@0.0.10, blacksmiths@0.2.0, bullseye@2.2.4, cats@1.3.4, feverstonehorses@1.2.6, packanimals@1.0.1, wildcraft@1.2.1, wolftaming@1.3.3, xskillspatched@0.6.9-dev.7
31.03.2022 3:21:51: Critical error occurred
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в ExpandedFoods.BlockSaucepan.GenRightMesh(ICoreClientAPI capi, ItemStack contentStack, BlockPos forBlockPos, Boolean isSealed)
   в ExpandedFoods.BlockSaucepan.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   в Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt)
   в Vintagestory.GameContent.EntityItemRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass)
   в Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderOpaque3D(Single deltaTime)
   в Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   в Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   в Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   в Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   в _4Bi1AGVssrIO0El8b8ygdS9FIfm._o5h005s1ovnxSPPqKWgI4tZUoCh(Single )
   в _lAuHsYOBOAjBMdATFXwLUtH7N00._JvY4M2412YZu1OS3Ull8wgZBu1j(Single )
   в _lAuHsYOBOAjBMdATFXwLUtH7N00._KmBeEx15nyyLrVqNDW6geSArpNr(Single )
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 479
   в OpenTK.GameWindow.DispatchRenderFrame() в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 454
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 375
   в _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   в _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )

**Comment by cyraxan** [comment]
updated to pre.6
still client crash at boiling soy milk

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.4 (Stable)
Loaded Mods: advancedsmithing@1.2.0, weaponpackapatch@2.0.0, ancienttools@1.4.0, animalcages@2.0.6, armorrepair@1.0.3, axleinblocks@1.0.12, betterdrifters@2.1.3, buildingplus@1.1.2, chiseltools@1.4.4, dragonflies@1.2.0, expandedfoods@1.5.3-pre.6, fieldsofgold@1.1.15, hammersringingfall@1.1.2-dev.1, potatoes@1.0.8, leadroof@1.1.1, necessaries@1.1.1, neededthings@1.0.0, nightwatcher@1.2.0, primitivesurvival@2.8.0, qptech@1.7.6, superfuel@2.0.7, locustmod@2.3.5, tradeomat@1.6.0, viesblocks@2.0.2, viescraftmachines@1.17.0, game@1.16.4, alchemy@1.6.3, carrycapacity@0.6.5, drifteroverhaul@1.0.0, fromgoldencombs@1.3.11, helvehammerext@1.2.0, hudclock@2.7.0, lichen@1.6.0, medievalexpansion@3.7.1, moreanimals@1.2.2, morebags@1.0.0, outlawmod@1.1.0, petai@1.4.2, playercorpse@1.3.1, stonequarry@1.6.5, tpnet@1.5.1, translocatorlocator@1.0.2, usefulstuff@2.3.2, creative@1.16.4, survival@1.16.4, wildfarming@1.2.7, workbenchexpansion@1.4.1, xlib@0.6.8, xmelee@0.0.10, blacksmiths@0.2.0, bullseye@2.2.4, cats@1.4.0, feverstonehorses@1.2.6, packanimals@1.0.1, wildcraft@1.2.2, wolftaming@1.4.0, xskillspatched@0.6.9-dev.7
06.04.2022 12:09:34: Critical error occurred
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в ExpandedFoods.BlockSaucepan.GenRightMesh(ICoreClientAPI capi, ItemStack contentStack, BlockPos forBlockPos, Boolean isSealed)
   в ExpandedFoods.BlockSaucepan.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   в Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt)
   в Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Boolean shading, Boolean origRotate, Boolean showStackSize)
   в Vintagestory.API.Client.GuiElementItemSlotGridBase.RenderInteractiveElements(Single deltaTime)
   в Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   в Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime)
   в Vintagestory.API.Client.GuiDialogBlockEntity.OnRenderGUI(Single deltaTime)
   в Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   в Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   в Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   в Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   в _4Bi1AGVssrIO0El8b8ygdS9FIfm._LvzIyYpsQCoC78JubjSO0HCjtTg(Single )
   в _lAuHsYOBOAjBMdATFXwLUtH7N00._JvY4M2412YZu1OS3Ull8wgZBu1j(Single )
   в _lAuHsYOBOAjBMdATFXwLUtH7N00._KmBeEx15nyyLrVqNDW6geSArpNr(Single )
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 479
   в OpenTK.GameWindow.DispatchRenderFrame() в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 454
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 375
   в _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   в _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )

**Comment by l33tmaan** [comment]
Are you still getting this crash on pre.7?
