### ISSUE TITLE
Missing entries for expandedfoods:choppedmushroom-bolete in multiple recipes

### ISSUE THREAD

**Issue by PhyDoesStuff** [l33tmaan/vs-expandedfoods#14]
Mod version: v1.5.3-pre.11
Game version: 1.16.5

Log entries in server-main.txt indicate that multiple recipes are missing entries for  `expandedfoods:choppedmushroom-bolete` in 
- game:recipes/cooking/meatystew.json
- game:recipes/cooking/porridge.json
- game:recipes/cooking/scrambledeggs.json
- game:recipes/cooking/soup.json
- game:recipes/cooking/vegetablestew.json
- game:recipes/cooking/augratin.json
- game:recipes/cooking/pastahot.json
- game:recipes/cooking/riceandbeans.json
- expandedfoods:recipes/mixing/pastacold.json
- expandedfoods:recipes/mixing/salad.json

I've attached server-main.txt for review: [server-main.txt](https://github.com/l33tmaan/vs-expandedfoods/files/8882768/server-main.txt)

**Comment by l33tmaan** [comment]
Should be fixed in 1.5.3.

**Comment by PhyDoesStuff** [comment]
Confirmed, 1.5.3 no longer produces these log entries.
