### ISSUE TITLE
Missing entries for expandedfoods:acornbreadedfishnugget-*

### ISSUE THREAD

**Issue by PhyDoesStuff** [l33tmaan/vs-expandedfoods#17]
Mod version: v1.5.3-pre.11
Game version: 1.16.5

- `expandedfoods:acornbreadedfishnugget-smashed` has errors in `expandedfoods:recipes/kneading/acorns/acornbreadedfishnuggetoiled.json`
- `expandedfoods:acornbreadedfishnugget-oiled` has errors in `expandedfoods:recipes/kneading/acorns/acornbreadedfishnuggetoiled.json`
- `expandedfoods:acornbreadedfishnugget-syruppartbaked` has errors in `expandedfoods:recipes/kneading/acorns/acornbreadedfishnuggetsyrup.json`
- `expandedfoods:acornbreadedfishnugget-tender` has errors in `expandedfoods:recipes/kneading/acorns/acornbreadedfishnuggetsyrup.json`
- `expandedfoods:acornbreadedfishnugget-syrups` has errors in `expandedfoods:recipes/kneading/acorns/acornbreadedfishnuggetsyrup.json`
- `expandedfoods:acornbreadedfishnugget-charred` has errors in `expandedfoods:recipes/kneading/acorns/acornbreadedfishnuggetsyrup.json`
- `expandedfoods:acornbreadedfishnugget-syrupcharred` has errors in `expandedfoods:recipes/kneading/acorns/acornbreadedfishnuggetsyrup.json`

See server-main.txt: [server-main.txt](https://github.com/l33tmaan/vs-expandedfoods/files/8882780/server-main.txt)

**Comment by l33tmaan** [comment]
Should be fixed in 1.5.3.

**Comment by PhyDoesStuff** [comment]
Confirmed, no longer seeing these log entries in 1.5.3.
