### ISSUE TITLE
Missing entry for expandedfoods:acornportion

### ISSUE THREAD

**Issue by PhyDoesStuff** [l33tmaan/vs-expandedfoods#18]
Mod version: v1.5.3-pre.11
Game version: 1.16.5

`10.6.2022 18:45:40 [Warning] Failed resolving crafting recipe ingredient with code expandedfoods:acornportion in kneading recipe expandedfoods:recipes/kneading/wildcraft/herbstuff/acorngozinaki.json` twice in the logs

[server-main.txt](https://github.com/l33tmaan/vs-expandedfoods/files/8882782/server-main.txt)

**Comment by l33tmaan** [comment]
Should be fixed in 1.5.3.

**Comment by PhyDoesStuff** [comment]
Confirmed, no longer seeing in 1.5.3.
