### ISSUE TITLE
Crash while making pies

### ISSUE THREAD

**Issue by VinterNacht** [l33tmaan/vs-expandedfoods#9]
Crash occurring on the Wilderlands server.  Not sure how much this is directly related to your mod, but it's in the report!

[client-crash.txt](https://github.com/l33tmaan/vs-expandedfoods/files/8373749/client-crash.txt)

**Comment by l33tmaan** [comment]
What were the ingredients you were using to make the pie?

**Comment by VinterNacht** [comment]
Spelt Flour, cranberries, and bramble berries, as the person who crashed recalls.

**Comment by l33tmaan** [comment]
... bramble berries?

**Comment by l33tmaan** [comment]
Hey, I've been making pies lately without any crashing. Have you gotten this problem recently?

**Comment by VinterNacht** [comment]
Nope.

**Comment by l33tmaan** [comment]
Works for me!
